"""add crawl_runs table and resync_count

Revision ID: a99d9d52b67b
Revises: 002_trade_history
Create Date: 2026-03-15 14:27:48.962442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a99d9d52b67b'
down_revision: Union[str, None] = '002_trade_history'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('copy_orders', 'is_paper',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('copy_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('copy_signals', 'previous_size',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('copy_signals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('crawl_progress', 'activities_crawled',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('crawl_progress', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'''PENDING'''::character varying"))
    op.alter_column('leaderboard_snapshots', 'captured_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('markets', 'volume',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('markets', 'liquidity',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('markets', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('markets', 'settled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('markets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('markets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('portfolio_snapshots', 'captured_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('position_snapshots', 'captured_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trader_positions', 'first_detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trader_positions', 'last_updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('traders', 'composite_score',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('traders', 'best_pnl_all_time',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('traders', 'best_pnl_monthly',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('traders', 'best_pnl_weekly',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('traders', 'best_pnl_daily',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('traders', 'total_trades',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('traders', 'is_watched',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('traders', 'first_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('traders', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('traders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('traders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('traders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('traders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('traders', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('traders', 'first_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('traders', 'is_watched',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('traders', 'total_trades',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('traders', 'best_pnl_daily',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('traders', 'best_pnl_weekly',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('traders', 'best_pnl_monthly',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('traders', 'best_pnl_all_time',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('traders', 'composite_score',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('trader_positions', 'last_updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trader_positions', 'first_detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('position_snapshots', 'captured_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('portfolio_snapshots', 'captured_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('markets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('markets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('markets', 'settled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('markets', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('markets', 'liquidity',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('markets', 'volume',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('leaderboard_snapshots', 'captured_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('crawl_progress', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'''PENDING'''::character varying"))
    op.alter_column('crawl_progress', 'activities_crawled',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('copy_signals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('copy_signals', 'previous_size',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('copy_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('copy_orders', 'is_paper',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('app_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
